### PR TITLE
remove shitty code

### PR DESCRIPTION
**Pull request by SergejKembel**
https://www.youtube.com/embed/dQw4w9WgXcQ

https://youtu.be/WDiB4rtp1qw?t=287

### CODE REVIEW

**Comment by Tymonsky** [comment]
nie zesraj sie

**Comment by thelooter** [comment]
> https://www.youtube.com/embed/dQw4w9WgXcQ
> 
> https://youtu.be/WDiB4rtp1qw?t=287

LGTM

**Review by neverabsolute — APPROVED** [review]
LGTM

**Comment by SergejKembel** [comment]
Any update here? KEKW

**Pull request closed without merging**
